# Generated by Django 4.2.2 on 2023-06-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_icecream', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Icecream_Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Icecream_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField()),
                ('sales', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('icecream_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.icecream')),
                ('icecream_shop_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clients')),
                ('icecream_shop_taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.icecream_taste')),
            ],
        ),
    ]
