# Generated by Django 4.2.2 on 2023-06-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream_shop',
            old_name='icecream_shop',
            new_name='icecream',
        ),
        migrations.RenameField(
            model_name='icecream_shop',
            old_name='icecream_shop_clients',
            new_name='icecream_clients',
        ),
        migrations.RenameField(
            model_name='icecream_shop',
            old_name='icecream_shop_taste',
            new_name='icecream_taste',
        ),
    ]
