# Generated by Django 4.2.2 on 2023-06-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_icecream_shop_icecream_shop_icecream_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream_shop',
            old_name='icecream_clients',
            new_name='clients',
        ),
        migrations.RenameField(
            model_name='icecream_shop',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
